#### **IMPORTAR NUMPY**

In [5]:
import numpy as np

##### **CREANDO LISTA**

In [7]:
lista = [1,3,5,7,9,2]
lista

[1, 3, 5, 7, 9, 2]

##### **TRANSFORMANDO**

In [8]:
arreglo = np.array(lista)
arreglo

array([1, 3, 5, 7, 9, 2])

In [9]:
type(arreglo)

numpy.ndarray

#### Tipo de datos del arreglo


In [10]:
arreglo.dtype

dtype('int32')

#### **Definiendo** el Array de int32 a float32

In [11]:
np.array(arreglo, dtype=np.float32)

array([1., 3., 5., 7., 9., 2.], dtype=float32)

#### El arreglo no se transformo

In [14]:
arreglo

array([1, 3, 5, 7, 9, 2])

#### **TRANFORMAR**


In [13]:
arreglo.astype(np.float32)

array([1., 3., 5., 7., 9., 2.], dtype=float32)

#### **Generar solo unos**

In [17]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos.astype(np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### ESTADISTICA

In [24]:
np.median(arreglo)

4.0

In [25]:
np.mean(arreglo)

4.5

In [88]:
np.std(arreglo)

2.8136571693556887

#### Generando arreglo aleatorio

In [33]:
random_arreglo = np.random.rand(5)
random_arreglo

array([0.43671909, 0.13438735, 0.90808298, 0.8541479 , 0.77258154])

#### Generando *Matriz* aleatoria

In [37]:
matriz_random = np.random.rand(3,3)
matriz_random

array([[0.04499167, 0.41948299, 0.42115802],
       [0.40138083, 0.11486851, 0.66605428],
       [0.00136726, 0.16931822, 0.11720595]])

#### Random con numeros enteros

In [76]:
random_arreglo2 = np.random.randint(1,100,5)
random_arreglo2

array([83, 53, 55, 18, 25])

In [87]:
matriz_random2 = np.random.randint(1,100,(5,5))
matriz_random2

array([[57, 98, 64, 90, 28],
       [55, 35, 48, 48, 39],
       [ 3, 89, 36, 74,  1],
       [69, 96, 40, 98, 46],
       [34, 30, 37, 48, 52]])