#### **IMPORTAR NUMPY**

In [2]:
import numpy as np

##### **CREANDO LISTA**

In [3]:
lista = [1,3,5,7,9,2]
lista

[1, 3, 5, 7, 9, 2]

##### **TRANSFORMANDO**

In [4]:
arreglo = np.array(lista)
arreglo

array([1, 3, 5, 7, 9, 2])

In [5]:
type(arreglo)

numpy.ndarray

#### Tipo de datos del arreglo


In [6]:
arreglo.dtype

dtype('int32')

#### **Definiendo** el Array de int32 a float32

In [7]:
np.array(arreglo, dtype=np.float32)

array([1., 3., 5., 7., 9., 2.], dtype=float32)

#### El arreglo no se transformo

In [8]:
arreglo

array([1, 3, 5, 7, 9, 2])

#### **TRANFORMAR**


In [9]:
arreglo.astype(np.float32)

array([1., 3., 5., 7., 9., 2.], dtype=float32)

#### **Generar solo unos**

In [10]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos.astype(np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### ESTADISTICA

In [11]:
np.median(arreglo)

4.0

In [12]:
np.mean(arreglo)

4.5

In [13]:
np.std(arreglo)

2.8136571693556887

#### Generando arreglo aleatorio

In [14]:
random_arreglo = np.random.rand(5)
random_arreglo

array([0.01915645, 0.7561871 , 0.4345923 , 0.07768385, 0.95459128])

#### Generando *Matriz* aleatoria

In [15]:
matriz_random = np.random.rand(3,3)
matriz_random

array([[0.26570691, 0.10768029, 0.96409289],
       [0.70520637, 0.94919414, 0.33539988],
       [0.99811417, 0.19052798, 0.79622595]])

#### Random con numeros enteros

In [16]:
random_arreglo2 = np.random.randint(1,100,5)
random_arreglo2

array([79, 95, 19, 51, 96])

In [17]:
matriz_random2 = np.random.randint(1,100,(5,5))
matriz_random2

array([[59, 81, 64, 10, 13],
       [82,  7, 98, 81, 89],
       [72, 46, 37, 49, 39],
       [83, 18, 82, 44, 18],
       [13, 81, 18,  1, 18]])

#### **Mas Estadistica**

In [18]:
np.max(random_arreglo2)

96

In [22]:
np.percentile(random_arreglo2,50)

79.0